name:                PenroseKiteDart
version:             0.5.2.0
github:              "chrisreade/PenroseKiteDart"
license:             BSD3
author:              "Chris Reade"
maintainer:          "chrisreade@mac.com"
copyright:           "2021 Chris Reade"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:  Library to explore Penrose's Kite and Dart Tilings.
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:  Please see the README on GitHub at <https://github.com/chrisreade/PenroseKiteDart#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams-lib
- diagrams-contrib
- diagrams-svg
- diagrams-rasterific # added for alternative backend
- diagrams-postscript # added for postscript output
- containers # added for Data.Map
library:
  source-dirs: src
  exposed-modules:  
    - PKD
    - HalfTile
    - TileLib
    - Tgraphs
    - Tgraph.Prelude
    - Tgraph.Decompose
    - Tgraph.Compose
    - Tgraph.Force
    - Tgraph.Relabelling
    - TgraphExamples
    - TestIllustrate
    - ArtWork
executables:
  PenroseKiteDart-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: 
    - PenroseKiteDart
    when:        
    - condition: false        
      other-modules: Paths_PenroseKiteDart
tests:
  PenroseKiteDart-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PenroseKiteDart
    - hspec
benchmarks:
  PenroseKiteDart-bench:
    main:                Bench.hs
    source-dirs:         benchmark
    ghc-options:
#    - -O2 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PenroseKiteDart
